/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class joe_com_blurlibrary_BlurCore */

#ifndef _Included_joe_com_blurlibrary_BlurCore
#define _Included_joe_com_blurlibrary_BlurCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     joe_com_blurlibrary_BlurCore
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)I
 */
JNIEXPORT jint JNICALL Java_joe_com_blurlibrary_BlurCore_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
